// Copyright 2025 The Go MCP SDK Authors. All rights reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

// FORK: distributed-sessions
// This file implements the SessionBackend interface for distributed
// session management across multiple server replicas.

package mcp

import (
	"context"
	"errors"
)

// ErrSubscriptionSuperseded is returned by Subscribe when another subscriber
// took over the session's message stream. This typically happens during
// failover when a new pod claims ownership of the session.
var ErrSubscriptionSuperseded = errors.New("mcp: subscription superseded")

// ErrSessionNotFound is returned when a session lookup fails because the
// session does not exist in the backend.
var ErrSessionNotFound = errors.New("mcp: session not found")

// SessionData holds the persistent state for a distributed session.
// This data is stored in the SessionBackend and can be retrieved by any
// server replica.
type SessionData struct {
	// SessionID is the unique identifier for this session, generated by
	// the SessionBackend.Create method.
	SessionID string `json:"sessionId"`

	// State contains the MCP protocol state for the session.
	State *ServerSessionState `json:"state,omitempty"`

	// UserID is the authenticated user ID, used to prevent session hijacking.
	// If non-empty, subsequent requests must have the same user ID.
	UserID string `json:"userId,omitempty"`
}

// MessageHandler is called by Subscribe for each message that needs to be
// delivered to the session's SSE stream.
//
// Return nil to acknowledge the message (it will be removed from the queue).
// Return an error to signal delivery failure (message may be redelivered).
type MessageHandler func(ctx context.Context, msg []byte) error

// SessionBackend provides session persistence and cross-pod message routing
// for multi-replica MCP server deployments.
//
// Implementations must be safe for concurrent use by multiple goroutines.
//
// The interface combines two responsibilities:
//  1. Session CRUD: Persisting session metadata so any replica can handle requests
//  2. Message routing: Delivering messages from non-owner pods to the SSE-owner pod
//
// Example flow for a distributed deployment:
//  1. Client connects to Pod A, which calls Create() and stores session
//  2. Client's SSE stream connects to Pod A, which calls Subscribe()
//  3. Client's POST request hits Pod B (via load balancer)
//  4. Pod B calls Get() to find the session, then Publish() to route the response
//  5. Pod A's Subscribe handler receives the message and writes to SSE
type SessionBackend interface {
	// Create persists a new session and returns its unique ID.
	// The implementation generates the session ID (e.g., UUID, ULID).
	//
	// The returned ID must be globally unique across all sessions.
	Create(ctx context.Context, data *SessionData) (string, error)

	// Get retrieves session data by ID.
	// Returns ErrSessionNotFound if the session does not exist.
	Get(ctx context.Context, id string) (*SessionData, error)

	// Update persists changes to an existing session.
	// The SessionID field in data must match id.
	// Returns ErrSessionNotFound if the session does not exist.
	Update(ctx context.Context, id string, data *SessionData) error

	// Delete removes a session from the backend.
	// This should also clean up any associated message queues.
	// Returns nil if the session does not exist (idempotent).
	Delete(ctx context.Context, id string) error

	// Touch updates the session's last activity timestamp without
	// modifying other data. Called on each POST request to signal activity.
	//
	// Backend implementations SHOULD use this to extend the session's TTL.
	// For example, a Redis implementation might call EXPIRE to reset the TTL.
	// This is the primary mechanism for distributed session timeout management,
	// since local timers are lost on pod restarts.
	//
	// Returns ErrSessionNotFound if the session does not exist.
	Touch(ctx context.Context, id string) error

	// Publish sends a message to the session's message queue.
	// The message will be delivered to the Subscribe handler on the
	// pod that owns the session's SSE stream.
	//
	// Messages are delivered in FIFO order per session.
	Publish(ctx context.Context, sessionID string, msg []byte) error

	// Subscribe starts receiving messages for a session.
	//
	// The handler is called for each message in order. Subscribe blocks
	// until one of:
	//   - ctx is cancelled: returns ctx.Err()
	//   - handler returns an error: returns that error (message not acked)
	//   - another subscriber takes over: returns ErrSubscriptionSuperseded
	//   - session is deleted: returns ErrSessionNotFound
	//
	// When handler returns nil, the message is acknowledged and removed
	// from the queue. When handler returns an error, the message may be
	// redelivered to another subscriber.
	//
	// Only one subscriber should be active per session at a time.
	// Implementations may enforce this by returning ErrSubscriptionSuperseded
	// to the previous subscriber when a new one connects.
	Subscribe(ctx context.Context, sessionID string, handler MessageHandler) error
}
